### ISSUE TITLE
Faster webp lossless write

### ISSUE THREAD

**Issue by surruit** [lquesada/ComfyUI-Prompt-Combinator#3]
When writing in lossless Webp format, its very slow.

Saving 54 images of size 512x512 in webp lossless:
`Prompt executed in 187.36 seconds`

Saving 54 images of size 512x512 in webp q90:
`Prompt executed in 2.29 seconds`

Just by changing this value from 100 to 0, it runs faster:
https://github.com/lquesada/ComfyUI-Prompt-Combinator/blob/dd423316ce5ae80d520861dd000f90a4afc59349/prompt_combinator.py#L317

Saving 54 images of size 512x512 in webp lossless (quality value 0):
`Prompt executed in 4.17 seconds`

It only changes the size of the file, as the documentation explains:

> **quality**
> Integer, 0-100, defaults to 80. For lossy, 0 gives the smallest size and 100 the largest. For lossless, this parameter is the amount of effort put into the compression: 0 is the fastest, but gives larger files compared to the slowest, but best, 100.
> 

https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#webp

Total file size lossless q100 (54 images 512x512): 13.8 MB
Total file size lossless q0 (54 images 512x512): 14.2MB

Total file size lossless q100 (54 images 2048x2048): 129 MB
Total file size lossless q0 (54 images 2048x2048): 130 MB

**Comment by lquesada** [comment]
thanks a lot! just fixed :)
